# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_callinfo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinfo',
            name='interval',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
